export default {

    GET_DEFAULT_CITY: "GET_DEFAULT_CITY",
    GET_DEFAULT_CITY_PENDING: "GET_DEFAULT_CITY_PENDING",
    GET_DEFAULT_CITY_SUCCESS: "GET_DEFAULT_CITY_SUCCESS",


    SEARCH_CITY_BY_NAME: "SEARCH_CITY_BY_NAME",
    SEARCH_CITY_BY_NAME_FAILURE: "SEARCH_CITY_BY_NAME_FAILURE",
    SEARCH_CITY_BY_NAME_REQUEST: "SEARCH_CITY_BY_NAME_REQUEST",

    GET_CITY_WEATHER: "GET_CITY_WEATHER",

    SAVE_KEY_OF_CITY: "SAVE_KEY_OF_CITY",

    ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
    REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE",

}