export default {

    GET_DEFAULT_CITY: "GET_DEFAULT_CITY",
    GET_DEFAULT_CITY_PENDING: "GET_DEFAULT_CITY_PENDING",
    GET_DEFAULT_CITY_SUCCESS: "GET_DEFAULT_CITY_SUCCESS",


    SEARCH_CITY_BY_NAME: "SEARCH_CITY_BY_NAME"

}